[package]
name = "mvtrs"
version = "0.4.1"
edition = "2021"
authors = ["Jose Jachuf <jjachuf@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "mvt_server"
path = "src/mvt_server/main.rs"

[[bin]]
name = "mvt_admin"
path = "src/mvt_admin/main.rs"

[dependencies]
uuid = { version = "1.8.0", features = ["v4", "fast-rng"] }
dotenv = "0.15.0"
clap = "4.4"
bytes = "1.5.0"
argon2 = { version = "0.5", features = ["std"] }
askama = "0.12.1"
anyhow = "1"
thiserror = "1"
base64 = "0.22"
log = "0.4"
time = "0.3"
jsonwebtoken = "9.1.0"
chrono = { version = "0.4", features = ["serde"] }
salvo = { version = "0.72", features = ["cors", "logging", "cache", "anyhow", "basic-auth", "jwt-auth", "serve-static"] }
tokio = { version = "1", features = ["macros"] }
tracing = "0.1"
tracing-subscriber = {version="0.3", features = ["json", "env-filter"] }
serde_json = "1"
serde = { version = "1", features = ["derive"] }
sqlx = { version = "0.8", features = [ "runtime-tokio-native-tls" , "postgres", "sqlite" ] }

redis = { version = "0.27", features = ["tokio-comp"] }
bb8 = "0.8"
bb8-redis = "0.17"
# surrealdb = "1.5.4"

[profile.release]
opt-level = 'z' # Optimize for size
lto = true
codegen-units = 1
